### ISSUE TITLE
Partials don't reload on save

### ISSUE THREAD

**Issue by EmperorAndross** [johnknoop/vscode-handlebars-preview#51] opened 2022-11-30 03:46 UTC
We're having an issue with the preview not refreshing when a partial is changed. The template update works exactly as advertised, however, the only way we can get a partial to update is to close VS Code, and then reopen it and show the preview again. Nothing else seems to work. This makes development quite tedious.
This behaviour is the same on three different computers with different VS code setups.

**Comment by johnknoop** [comment] 2022-11-30 09:34
Hi @EmperorAndross 

I can verify what you are seeing. This is definitely a regression. Hard to tell when this stopped working as I don't use the extension very often myself. It may be something in the underlying VS Code API that has changed. I'll look into it as soon as possible.

**Comment by johnknoop** [comment] 2022-11-30 12:44
@EmperorAndross the issue is now fixed and a new version has been published to VS Code marketplace.

**Closed by johnknoop** 2022-11-30 12:44 UTC

**Comment by EmperorAndross** [comment] 2022-12-01 03:57
@johnknoop Thank you for your very quick response! Excellent update

**Comment by xtrinch** [comment] 2024-05-15 13:54
This appears to once again be the case - I must close VSCode in order to register any changes in partials

**Comment by johnknoop** [comment] 2024-06-13 07:26
@xtrinch 

I was able to reproduce it a few weeks ago, but today when I sat down to have a look at it, I can no longer reproduce it. It must have been fixed in a subsequent VS Code update. Can you confirm?
